name: Deploy

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install and Build 🔧
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: generated # The branch the action should deploy to.
          folder: docs/.vitepress/dist # The folder the action should deploy.